### ISSUE TITLE
Dynamic Darkness - Crash during initialization 

### ISSUE THREAD

**Issue by Sereath** [yamporg/mods#1] opened 2021-03-07 10:55 UTC
### What version are you using?

I’m using file darkness-forge-1.12.x-0.4.0.jar from CurseForge.

### Does this issue reproduce with the latest release?

Yes it does.

### Which other mods do you have installed?

Around 350, however according to the crash log (my interpretation) forge only manages to load 6 of them before crashing.

       | State | ID                | Version        | Source                                  | Signature                                |
       |:----- |:----------------- |:-------------- |:--------------------------------------- |:---------------------------------------- |
       |       | minecraft         | 1.12.2         | minecraft.jar                           | None                                     |
       |       | mcp               | 9.42           | minecraft.jar                           | None                                     |
       |       | FML               | 8.0.99.99      | forge-1.12.2-14.23.5.2854-universal.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       |       | forge             | 14.23.5.2854   | forge-1.12.2-14.23.5.2854-universal.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       |       | creativecoredummy | 1.0.0          | minecraft.jar                           | None                                     |
       |       | entity_culling    | 3.0.1          | minecraft.jar                           | None                                     |
       |       | ivtoolkit         | 1.3.3-1.12     | minecraft.jar                           | None                                     |
       |       | littletilescore   | 1.0.0          | minecraft.jar                           | None                                     |
       |       | smoothfontcore    | mc1.12.2-2.1.2 | minecraft.jar                           | None                                     |
       |       | openmodscore      | 0.12.2         | minecraft.jar                           | None                                     |

Crash logs:

[crash-2021-03-07_04.28.14-client.txt](https://github.com/yamporg/mods/files/6096951/crash-2021-03-07_04.28.14-client.txt)

[crash-2021-03-07_04.30.09-client.txt](https://github.com/yamporg/mods/files/6096952/crash-2021-03-07_04.30.09-client.txt)
+
[2021-03-07-6.log](https://github.com/yamporg/mods/files/6096960/2021-03-07-6.log)
[debug-1.log](https://github.com/yamporg/mods/files/6096961/debug-1.log)
       
Modlist:

https://gist.github.com/Aeron216/4a0fe1747533917d2efb9f0f73639530

Note: This file was generated after putting back Hardcore Darkness instead of Dynamic Darkness.

### What did you do?

1. Added Dynamic Darkness to my mod folder.
2. Launch the modded instance.
3. Game crashes within seconds.

Minecraft Forge stops crashing only after removing Dynamic Darkness.

### What did you expect to see?

For the game to fully load.

### What did you see instead?

Minecraft crashes in just mere seconds of forge initializing.

**Comment by Sereath** [comment] 2021-03-07 11:06
And this is what I get with the previous release, darkness-0.3.1.jar

[debug.log](https://github.com/yamporg/mods/files/6096971/debug.log)

No crash log, just that.

**Comment by tie** [comment] 2021-03-08 13:44
Thanks for report! Looks like either I’m doing [loading resources](https://github.com/yamporg/mods/blob/69c9a964e73f297e3b5fd365b8b5d748f983e707/darkness-forge-1.12.x/src/main/java/io/github/yamporg/darkness/ModContainer.java#L22-L26) the wrong way or another coremod tinkers with class/resource loading.

~~Are you playing a modpack that is available on CurseForge? It’d help a lot if I had a setup to reproduce the crash.~~

Can reproduce the issue on a local [DDSS](https://www.curseforge.com/minecraft/modpacks/dungeons-dragons-and-space-shuttles) instance.

**Comment by tie** [comment] 2021-03-08 14:07
Can reproduce with `CreativeCore_v1.10.16_mc1.12.2.jar` alone.

**Comment by Sereath** [comment] 2021-03-09 01:56
Glad to see that you could reproduce it since I still haven't uploaded this modpack to curseforge.

**Comment by tie** [comment] 2021-03-09 20:01
Should be fixed in v0.4.1, release is available on [CurseForge](https://www.curseforge.com/minecraft/mc-mods/dynamic-darkness/files/3233380) and [GitHub](https://github.com/yamporg/mods/releases/tag/darkness-forge-1.12.x%2Fv0.4.1) 🎉

Let me know if that didn’t solve the issue for you.

**Closed as completed by tie** 2021-03-09 20:01 UTC
Labels: bug

**Comment by Sereath** [comment] 2021-03-11 02:40
Working now, thank you.
